#!/bin/bash

DIR="${1:-.}"
COUNT=1

if [ -d "$DIR" ]; then
  cd "$DIR" || exit
  for file in *.jpg *.png *.jpeg; do
    [ -e "$file" ] || continue
    mv "$file" "image_$COUNT.${file##*.}"
    ((COUNT++))
  done
  echo "Renamed $((COUNT-1)) image files."
else
  echo "Directory not found: $DIR"
fi
